name: Lint

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: チェックアウト
        uses: actions/checkout@v2

      - name: Node.jsのセットアップ
        uses: actions/setup-node@v2
        with:
          node-version: 17 # 必要に応じてNode.jsのバージョンを調整してください。

      - name: 依存関係のインストール
        run: yarn --frozen-lockfile

      - name: Yarn Lintの実行
        run: yarn lint
